In [17]:
import numpy as np
import scipy.signal 

In [25]:
kernel = np.ones((3,3))
kernel

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
M = np.ones((8,8))
M

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [29]:
Conv = scipy.signal.convolve2d(M,kernel, mode = 'valid')

In [30]:
Conv

array([[9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9.]])